---
apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: inventory-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-deployment
  template:
    metadata:
      labels:
        app: inventory-deployment
    spec:
      containers:
      - image: {{ INVENTORY_TAG }}
        name: inventory
        command: ["sleep", "infinity"]
      - image: {{ INVENTORY_TAG }}
        name: authenticator
        command: ["sleep", "infinity"]
