FROM phusion/baseimage:0.9.22

RUN apt-get update -y && \
    apt-get install -y software-properties-common && \
    apt-add-repository -y ppa:brightbox/ruby-ng && \
    apt-get update -y
    
RUN apt-get install -y \
    build-essential \
    ruby2.2 ruby2.2-dev \
    postgresql-client \
    libpq-dev \
    unattended-upgrades \
    ldap-utils \
    git \
    update-notifier-common \
    vim \
    curl \
    jq \
    tzdata
      
RUN gem install -N -v 1.11.2 bundler

RUN mkdir -p /src/conjur/server

ADD .irbrc /root

WORKDIR /src/conjur/server

ADD Gemfile      .
ADD Gemfile.lock .

RUN bundle

RUN rm /etc/service/sshd/down
RUN ln -sf /src/conjur/server/bin/conjurctl /usr/local/bin/

ENV PORT 3000
ENV TERM xterm

EXPOSE 3000
