# Build from the same version of ubuntu as phusion/baseimage
FROM @@image@@

RUN apt-get update -y && \
    apt-get install -y zlib1g-dev \
                       liblzma-dev

ENV BUNDLER_VERSION 2.2.18
RUN gem install --no-rdoc --no-ri bundler:$BUNDLER_VERSION fpm

RUN mkdir -p /src/opt/conjur/project

WORKDIR /src/opt/conjur/project

COPY Gemfile \
     Gemfile.lock ./
COPY gems/ gems/

COPY . .
ADD debify.sh /

WORKDIR /src
