FROM ruby:2.6-alpine

RUN apk update
RUN apk upgrade
RUN apk add git
RUN rm -rf /var/cache/apk/*

RUN mkdir -p /src/
WORKDIR /src/

COPY ./ /src/
RUN gem install -N bundler gem-licenses
RUN bundle install
