#!/bin/bash -ex

# build the image
./build.sh

pushd dev
  # start Conjur with the CONJUR_AUTHENTICATORS env var set
#  export CONJUR_AUTHENTICATORS=authn-ldap/test,authn-k8s/gke/prod,authn-cf/pcf/prod
  export CONJUR_AUTHENTICATORS=authn-ldap/test
  ./start.sh

  docker exec conjurdev_conjur_1 conjurctl wait -r 30 -p 3000

  # load the sample policy
  api_key=$(docker exec conjurdev_conjur_1 bash -c 'rails r "puts Role[%Q{cucumber:user:admin}].api_key" 2>/dev/null')
  docker exec \
    -e CONJUR_AUTHN_API_KEY=$api_key \
    conjurdev_client_1 \
    bash -c 'conjur policy load root /src/conjur-server/dev/sample-ldap-policy.yml'
popd

pushd lib/authenticators/authn_ldap
  ./bin/start-containers
popd
