source 'https://rubygems.org'

# Declare your gem's dependencies in authn_ldap.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec
group :local do
  # gem 'authn_core', path: '../../gems/authn_core'
  gem 'authn_core', path: 'lib/gems/authn_core'
end
gem 'conjur-api', github: 'cyberark/conjur-api-ruby'

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]

