FROM cyberark/phusion-ruby-fips:latest

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
    build-essential \
    ldap-utils \
    git \
    jq \
    tzdata \
    libfontconfig1 \
    libfontconfig1-dev
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    unattended-upgrades \
    vim \
    curl \
    wget \
    syslog-ng \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /src/conjur-server

ADD .pryrc /root

WORKDIR /src/conjur-server

COPY Gemfile \
     Gemfile.lock ./
COPY gems/ gems/

RUN bundle

# removing CA bundle of httpclient gem
RUN find / -name httpclient -type d -exec find {} -name *.pem -type f -delete \;

RUN rm /etc/service/sshd/down
RUN ln -sf /src/conjur-server/bin/conjurctl /usr/local/bin/

ENV PORT 3000
ENV TERM xterm

EXPOSE 3000
