FROM registry.tld/ruby-fips-base-image-phusion:1.0.0

RUN DEBIAN_FRONTEND=noninteractive apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    postgresql-client \
    libpq-dev \
    unattended-upgrades \
    ldap-utils \
    git \
    update-notifier-common \
    vim \
    curl \
    jq \
    tzdata \
    wget \
    libfontconfig1 \
    libfontconfig1-dev \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /src/conjur-server

ADD .pryrc /root

WORKDIR /src/conjur-server

ADD Gemfile      .
ADD Gemfile.lock .

RUN bundle

RUN rm /etc/service/sshd/down
RUN ln -sf /src/conjur-server/bin/conjurctl /usr/local/bin/

ENV PORT 3000
ENV TERM xterm

EXPOSE 3000
