FROM ruby:2.3

RUN apt-get update -y && apt-get install -y unzip vim jq

RUN wget https://apt.puppetlabs.com/puppetlabs-release-pc1-trusty.deb \
  && dpkg -i puppetlabs-release-pc1-trusty.deb

RUN apt-get update -y && apt-get install -y puppet-agent \
  && update-alternatives --install /usr/bin/puppet puppet-agent /opt/puppetlabs/bin/puppet 100

WORKDIR /opt

RUN curl -L -o cli-ruby.zip https://github.com/conjurinc/cli-ruby/archive/possum.zip && \
  unzip cli-ruby.zip && \
  cd cli-ruby-possum && \
  bundle

RUN echo "alias conjur='bundle exec ./bin/conjur'" >> /root/.bashrc

WORKDIR /opt/cli-ruby-possum

ENTRYPOINT [ "bundle", "exec", "conjur" ]
