FROM phusion/baseimage:0.11

RUN DEBIAN_FRONTEND=noninteractive apt-get update -y && \
    apt -y install software-properties-common && \
    apt-add-repository ppa:brightbox/ruby-ng
RUN DEBIAN_FRONTEND=noninteractive apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    ruby2.5 ruby2.5-dev \
    postgresql-client \
    libpq-dev \
    unattended-upgrades \
    ldap-utils \
    git \
    update-notifier-common \
    vim \
    curl \
    jq \
    tzdata \
    wget \
    libfontconfig1 \
    libfontconfig1-dev \
    && rm -rf /var/lib/apt/lists/*

RUN gem install --no-document --version 2.1.4 bundler

RUN mkdir -p /src/conjur-server

ADD .pryrc /root

WORKDIR /src/conjur-server

COPY Gemfile \
     Gemfile.lock ./
COPY gems/ gems/

RUN bundle

RUN rm /etc/service/sshd/down
RUN ln -sf /src/conjur-server/bin/conjurctl /usr/local/bin/

ENV PORT 3000
ENV TERM xterm

EXPOSE 3000
