#!/bin/sh

echo "Fetching authorization code"

cd /authn-oidc/phantomjs/scripts
echo "Deleting authorization_code file"
rm -rf authorization_code || true

echo "Copying file keycloak_login.js"
cp -rf keycloak_login.js keycloak_login_tmp.js

echo "Replacing user and password in keycloak_login_tmp.js"

sed -i 's/TO_BE_REPLACED_USER/'"$1"'/g' keycloak_login_tmp.js
sed -i 's/TO_BE_REPLACED_PASSSWORD/'"$2"'/g' keycloak_login_tmp.js

echo "Running phantomjs script"
phantomjs --ignore-ssl-errors=true keycloak_login_tmp.js

echo "Script complete!"
