source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in authn_core.gemspec
gemspec
gem 'conjur-api', github: 'cyberark/conjur-api-ruby'
