#!/bin/sh

# This terminates the process and all of its child processes
kill_recurse() {
    for child_pid in $(pgrep -P "$1");
    do
        kill_recurse "$child_pid"
    done
    kill "$1"
}

conjur_server_pid=$(pgrep -f 'ruby /usr/local/bin/conjurctl server')
# Iterate over conjur server process
for pid in $conjur_server_pids;
do
  kill_recurse $pid
done
