source 'https://rubygems.org'

git_source(:github) { |name| "https://github.com/#{name}.git" }

gem 'jekyll', '>= 3.6.3'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'

group :development do
  gem 'pry'
end
