#!/usr/bin/env bash
set -e

# This is executed by the main "ci/test" script after cd-ing into "ci".
# shellcheck disable=SC1091
source "./shared.sh"

echo "NRK2 DOES THIS EVER RUN?" >&2
start_ldap_server

additional_services='ldap-server'
_run_cucumber_tests authenticators_ldap "$additional_services"
