#!/usr/bin/env bash
set -e

# This is executed by the main "ci/test" script after cd-ing into "ci".
# shellcheck disable=SC1091
source "./shared.sh"

read -ra parallel_services <<< "$(get_parallel_service 'testdb')"
additional_services=''
for service in "${parallel_services[@]}"; do
    if [[ "$additional_services" == '' ]]; then
        additional_services+="${service}"
    else
        additional_services+=" ${service}"
    fi
done

_run_cucumber_tests rotators "${additional_services}"
