#!/usr/bin/env bash
set -e

# This is executed by the main "ci/test" script after cd-ing into "ci".
# shellcheck disable=SC1091
source "./shared.sh"

read -ra parallel_services <<< "$(get_service_name_by_process 'testdb testdb2')"

_run_cucumber_tests rotators "${parallel_services[@]}"
