---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-pod-only
---
# This service account is used for testing authentication with an incorrect service-account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: other-service-account
---
apiVersion: v1
kind: Pod
metadata:
  name: inventory-pod
  labels:
    app: inventory-pod
spec:
  serviceAccountName: inventory-pod-only
  containers:
  - image: {{ INVENTORY_TAG }}
    imagePullPolicy: IfNotPresent
    name: inventory
    securityContext:
      allowPrivilegeEscalation: false
    command: ["sleep", "infinity"]
  - image: {{ INVENTORY_TAG }}
    imagePullPolicy: IfNotPresent
    name: authenticator
    command: ["sleep", "infinity"]
    securityContext:
      allowPrivilegeEscalation: false
---
# This pod is used to test that the injection fails on pods where the user doesn't
# permissions on the /etc/conjur/ssl directory and that the error is written to
# a log file in the container
apiVersion: v1
kind: Pod
metadata:
  name: inventory-no-ssl-dir
  labels:
    app: inventory-no-ssl-dir
spec:
  serviceAccountName: inventory-pod-only
  containers:
  - image: {{ INVENTORY_BASE_TAG }}
    imagePullPolicy: IfNotPresent
    name: inventory
    command: ["sleep", "infinity"]
    securityContext:
      allowPrivilegeEscalation: false
  - image: {{ INVENTORY_BASE_TAG }}
    imagePullPolicy: IfNotPresent
    name: authenticator
    securityContext:
      allowPrivilegeEscalation: false
    command: ["sleep", "infinity"]
