FROM ruby:3.0-slim

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y \
    build-essential

RUN gem install -N activesupport --version 6.1.4.4 && \
    gem install -N conjur-api --version 5.3.7 && \
    gem install -N conjur-cli --version 6.2.6 && \
    gem install -N sinatra

COPY inventory.rb usr/src/inventory.rb

ENV PORT 80

CMD [ "ruby", "/usr/src/inventory.rb" ]
