#!/usr/bin/env bash
set -e

# This file has an implicit dependency on the environment variables defined in
# "ci/docker-compose.yml" oidc-keycloak section.

# This is executed by the main "ci/test" script after cd-ing into "ci".
# shellcheck disable=SC1091
source "./shared.sh"
source "./keycloak/keycloak_functions.sh"

function main() {
  docker-compose up --no-deps -d pg conjur oidc-keycloak

  # We also run an ldap-server container for testing the OIDC & LDAP combined
  # use-case.  We can't run this use-case in a separate Jenkins step because
  # we'll have a port bind for keycloak.
  start_ldap_server

  wait_for_keycloak_server
  create_keycloak_users
  fetch_keycloak_certificate

  additional_services='ldap-server oidc-keycloak'
  _run_cucumber_tests authenticators_oidc "$additional_services" \
    _hydrate_keycloak_env_args
}

main
