#!/usr/bin/env bash
set -e

# This is executed by the main "ci/test" script after cd-ing into "ci".
# shellcheck disable=SC1091
source "./shared.sh"

# shellcheck disable=SC1091
source "./test_suites/authenticators_azure/check_dependencies.sh"

# The single arg is a nameref, which this function sets to an array containing
# items of the form "KEY=VAL".
_hydrate_azure_env_args() {
  # Note: Both shellcheck errors are just because arr is a nameref.
  # shellcheck disable=SC2178
  local -n arr=$1
  # shellcheck disable=SC2034
  arr=(
    "AZURE_TENANT_ID=$AZURE_TENANT_ID"
    "AZURE_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION_ID"
    "AZURE_RESOURCE_GROUP=$AZURE_RESOURCE_GROUP"
    "AZURE_AUTHN_INSTANCE_IP=$AZURE_AUTHN_INSTANCE_IP"
    "AZURE_AUTHN_INSTANCE_USERNAME=$AZURE_AUTHN_INSTANCE_USERNAME"
    "AZURE_AUTHN_INSTANCE_PASSWORD=$AZURE_AUTHN_INSTANCE_PASSWORD"
    "USER_ASSIGNED_IDENTITY=$USER_ASSIGNED_IDENTITY"
    "USER_ASSIGNED_IDENTITY_CLIENT_ID=$USER_ASSIGNED_IDENTITY_CLIENT_ID"
    "SYSTEM_ASSIGNED_IDENTITY=$SYSTEM_ASSIGNED_IDENTITY"
  )
}

# Note: We pass the name of the function as the last arg, since we're
# using namerefs.
_run_cucumber_tests authenticators_azure "" _hydrate_azure_env_args
