source 'https://rubygems.org'

gemspec

#ruby=ruby-2.2.4
#ruby-gemset=conjur-authn-ldap

# gem 'sinatra'
# gem 'conjur-api', '~> 5.1'
# gem 'net-ldap'
# gem 'sequel'
# gem 'pg'
# gem 'puma'
# gem 'activesupport'
# gem 'conjur-rack-heartbeat'
gem 'conjur-appliance-logging', git: "https://github.com/conjurinc/appliance-logging.git", branch: "master"

# group :development do 
# #  gem 'conjur-debify', '~> 1.0'
# #  gem 'conjur-cli'
#   gem 'pry'
#   gem 'cucumber'
#   gem 'rspec'
#   gem 'rspec-mocks'
#   gem 'rspec-expectations'
#   gem 'ladle'
#   gem 'simplecov'
#   gem "ci_reporter_rspec"
#   gem 'rest-client'
#   gem 'rerun'
# end
