#!/bin/bash -e

[ "$DEBUG" ] && set -x

while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -b|--brakeman)
    RUN_BRAKEMAN=true
    ;;
    -a|--gem-audit)
    RUN_GEM_AUDIT=true
    ;;
    *)
    ;;
esac
shift # past argument or value
done

. `dirname $0`/docker-utils.sh

if [[ $RUN_BRAKEMAN = true ]]; then
  docker_run codeclimate/codeclimate-brakeman:b804 brakeman -o brakeman/reports/brakeman-output.html
fi


if [[ $RUN_GEM_AUDIT = true ]]; then
  docker_run --network default codeclimate/codeclimate-bundler-audit bundle audit check --update
fi
