FROM ubuntu:14.04

RUN apt-get update -y

RUN apt-get install -y \
  postgresql-client \
  libpq-dev \
  ldap-utils \
  update-notifier-common \
  vim \
  curl \
  jq \
  git

# Install the Conjur CLI
RUN curl -o conjur.deb -sSL https://github.com/conjurinc/cli-ruby/releases/download/v5.2.3/conjur_5.2.3-1_amd64.deb && \
  dpkg -i conjur.deb

ENV PATH /opt/conjur/embedded/bin:$PATH
ENV TERM xterm
