#!/usr/bin/env bash
set -e

# Note: REPORT_ROOT dependency is defined here.
# This is executed by the main "ci/test" script after cd-ing into "ci".
# shellcheck disable=SC1091
source "./shared.sh"

$COMPOSE up --no-deps -d pg

_wait_for_pg pg

# Note: The nested, escaped double quotes are needed in case $REPORT_ROOT
# ever changes to a path containing a space.
$COMPOSE run -T --rm --no-deps cucumber -ec "
  bundle exec rake db:migrate

  rm -rf \"$REPORT_ROOT/spec/reports\"

  bundle exec env \"CI_REPORTS=$REPORT_ROOT/spec/reports\" \
    rspec --format progress --require ci/reporter/rspec \
    --format CI::Reporter::RSpecFormatter"
