#!/bin/bash

aglio_options=""

function showhelp() {
    cat <<EOF
Usage: generate-static-docs [OPTION]... [FILE]
Uses Aglio to generate static API documentation for Conjur CE.

  -h display this help and exit
  -w start a dev server to watch for file updates and auto-refresh in browser

The FILE argument specifies where to write output (default stdout).
EOF
    exit
}

while getopts 'whv' opt; do
    case $opt in
        h)
            showhelp;;
        w)
            aglio_options="$aglio_options -s -h 0.0.0.0 -p 3000";;
        v)
            aglio_options="$aglio_options --verbose";;
        *)
            showhelp;;
    esac
done
shift $((OPTIND-1))

file="${1:--}"

env PATH="/home/node/node_modules/.bin:$PATH" \
    sh -c "aglio $aglio_options --theme-template templates/index.jade --theme-style templates/css/layout-conjur.less -i src/api.md -o \"$file\""
