#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PATH="$PATH:$DIR/node_modules/.bin"

aglio_options=""

while getopts 'wh' opt; do
    case $opt in
        h)
            cat <<EOF
Usage: generate-static-docs [OPTION]... [FILE]
Uses Aglio to generate static API documentation for Conjur CE.

  -h display this help and exit
  -w start a dev server to watch for file updates and auto-refresh in browser

The FILE argument specifies where to write output (default stdout).
EOF
            exit;;
        w)
            aglio_options="$aglio_options -s";;
    esac
done
shift $((OPTIND-1))

file="${1:--}"

aglio $aglio_options -i src/api.md -o "$file"
