#!/usr/bin/env ruby
# frozen_string_literal: true

require 'aws-sdk-iam'

# Load the rails environment: https://stackoverflow.com/a/10317713
require_relative '../../../config/environment'

# NOTE: This file is meant to be run after manually testing aws.feature, so that
#       you can record the latest value of the AWS test account credentials -- they
#       may have rotated many times during your testing.
#
#           MAKE SURE YOU STOP THE CONJUR SERVER BEFORE RUNNING THIS FILE
#
#       Otherwise the values you record will be rotated away again and you'll be 
#       locked out of the AWS test account.

region = Secret.where(resource_id: "cucumber:variable:aws/region").last.value
id = Secret.where(resource_id: "cucumber:variable:aws/access_key_id").last.value
key = Secret.where(resource_id: "cucumber:variable:aws/secret_access_key").last.value
creds = { region: region, access_key_id: id, secret_access_key: key }

begin
  # Our test account has nothing but the describe_regions privilege
  Aws::EC2::Client.new(creds).describe_regions
  puts(<<~EOS)

    To add your credentials next time to a fresh dev cucumber container:

    export AWS_DEFAULT_REGION=#{region}
    export AWS_ACCESS_KEY_ID=#{id}
    export AWS_SECRET_ACCESS_KEY=#{key}
  EOS
rescue
  puts(<<~EOS)

    Your most recent AWS credentials in conjur do not work.

    You may be locked out of the account now.

    You can manually check if any of the previous credentials work by running
    the Secret model queries above, but looking at the 2nd to last.
  EOS

end
