source 'https://rubygems.org'

git_source(:github) { |name| "https://github.com/#{name}.git" }

gem 'github-pages', '~> 207'
gem 'jekyll', '= 3.9.0'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from', '~> 0.15.0'
gem 'jekyll-sitemap', '~> 1.4.0'

group :development do
  gem 'pry'
end
