source 'https://rubygems.org'

git_source(:github) { |name| "https://github.com/#{name}.git" }

gem 'github-pages', '~> 232'
gem 'jekyll', '= 3.10.0'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from', '~> 0.16.0'
gem 'jekyll-sitemap', '~> 1.4.0'
gem 'rexml', '>= 3.4.2'

group :development do
  gem 'pry'
end
